# Form implementation generated from reading ui file 'ManageCategories.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogManageCategories(object):
    def setupUi(self, DialogManageCategories):
        DialogManageCategories.setObjectName("DialogManageCategories")
        DialogManageCategories.resize(561, 298)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DialogManageCategories)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(50, -1, 50, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelManageCategories = QtWidgets.QLabel(parent=DialogManageCategories)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.labelManageCategories.setFont(font)
        self.labelManageCategories.setObjectName("labelManageCategories")
        self.verticalLayout.addWidget(self.labelManageCategories)
        self.scrollArea = QtWidgets.QScrollArea(parent=DialogManageCategories)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 416, 138))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayoutCategories = QtWidgets.QVBoxLayout()
        self.verticalLayoutCategories.setObjectName("verticalLayoutCategories")
        self.verticalLayout_3.addLayout(self.verticalLayoutCategories)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonAddNew = QtWidgets.QPushButton(parent=DialogManageCategories)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAddNew.sizePolicy().hasHeightForWidth())
        self.pushButtonAddNew.setSizePolicy(sizePolicy)
        self.pushButtonAddNew.setObjectName("pushButtonAddNew")
        self.horizontalLayout.addWidget(self.pushButtonAddNew)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(parent=DialogManageCategories)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.labelErrorMessage = QtWidgets.QLabel(parent=DialogManageCategories)
        self.labelErrorMessage.setEnabled(True)
        self.labelErrorMessage.setObjectName("labelErrorMessage")
        self.verticalLayout.addWidget(self.labelErrorMessage)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButtonCancel = QtWidgets.QPushButton(parent=DialogManageCategories)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_2.addWidget(self.pushButtonCancel)
        self.pushButtonConfirm = QtWidgets.QPushButton(parent=DialogManageCategories)
        self.pushButtonConfirm.setObjectName("pushButtonConfirm")
        self.horizontalLayout_2.addWidget(self.pushButtonConfirm)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(DialogManageCategories)
        QtCore.QMetaObject.connectSlotsByName(DialogManageCategories)

    def retranslateUi(self, DialogManageCategories):
        _translate = QtCore.QCoreApplication.translate
        DialogManageCategories.setWindowTitle(_translate("DialogManageCategories", "Dialog"))
        self.labelManageCategories.setText(_translate("DialogManageCategories", "Manage Categories"))
        self.pushButtonAddNew.setText(_translate("DialogManageCategories", "Add New"))
        self.labelErrorMessage.setText(_translate("DialogManageCategories", "Error Message"))
        self.pushButtonCancel.setText(_translate("DialogManageCategories", "Cancel"))
        self.pushButtonConfirm.setText(_translate("DialogManageCategories", "Confirm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogManageCategories = QtWidgets.QDialog()
    ui = Ui_DialogManageCategories()
    ui.setupUi(DialogManageCategories)
    DialogManageCategories.show()
    sys.exit(app.exec())
